import com.mbenabda.techwatch.testES.facts.weight.*
import com.mbenabda.techwatch.testES.facts.answers.illness.*
import com.mbenabda.techwatch.testES.facts.BlacklistedKindOfInstruments

rule "cannot weight heavy instruments with back pain"
when
    $limit: WeightLimit(value > 5)
    HasBackPain()
then
    $limit.setValue(Float.valueOf(5));
    update($limit);
end

rule "avoid woodwinds if you have breathing issues"
when
    HasBreathingIssues()
then
    insert(new BlacklistedKindOfInstruments("WOODWIND"));
    insert(new BlacklistedKindOfInstruments("BRASS"));
end
