import com.mbenabda.techwatch.testES.domain.Instrument
import com.mbenabda.techwatch.testES.facts.budget.*

rule "intrument is cheap"
when
    Budget( $threshold: value )
    $instrument : Instrument( averageLowEndPrice < $threshold)
then
    insert(new IsCheap($instrument.getName()));
end

rule "intrument is expensive"
when
    Instrument( $name: name)
    not IsCheap( instrumentName == $name)
then
    insert(new IsExpensive($name));
end


