import com.mbenabda.techwatch.testES.domain.Instrument
import com.mbenabda.techwatch.testES.facts.noise.*

rule "intrument is silent"
when
    LoudnessThreshold( $threshold: value )
    $instrument : Instrument( loudness < $threshold)
then
    insert(new IsSilent($instrument.getId()));
end

rule "intrument is loud"
when
    Instrument( $id: id)
    not IsSilent( instrumentId == $id)
then
    insert(new IsLoud($id));
end


