import com.mbenabda.techwatch.testES.domain.Instrument
import com.mbenabda.techwatch.testES.facts.noise.*
import com.mbenabda.techwatch.testES.facts.answers.lifestyle.*

rule "intrument is silent"
when
    LoudnessThreshold( $threshold: value )
    $instrument : Instrument( loudness < $threshold)
then
    insert(new IsSilent($instrument.getId()));
end

rule "intrument is loud"
when
    Instrument( $id: id)
    not IsSilent( instrumentId == $id)
then
    insert(new IsLoud($id));
end


rule "instrument too loud for appartment"
when
    LivesInAnAppartment()
    $instrument: Instrument()
    IsLoud(instrumentId == $instrument.getId())
then
    insert(new IsTooLoud($instrument.getId()));
end
