import com.mbenabda.techwatch.testES.domain.*
import com.mbenabda.techwatch.testES.facts.suggestion.*
import com.mbenabda.techwatch.testES.facts.weight.*
import com.mbenabda.techwatch.testES.facts.budget.*
import com.mbenabda.techwatch.testES.facts.dedication.*
import com.mbenabda.techwatch.testES.facts.storage.*
import com.mbenabda.techwatch.testES.facts.*
import com.mbenabda.techwatch.testES.facts.answers.*
import com.mbenabda.techwatch.testES.facts.instruments.*
import java.util.Arrays
import com.google.common.base.Joiner

rule "suggest genres"
when
    $dob: DateOfBirth()
    $genre: Genre()
    eval(wasYoungAdultDuringGoldenAge($dob, $genre))
then
    insert(new GenreSuggestion($genre));
end

rule "suggest instruments"
when
    $instrument: Instrument()
    not InstrumentSuggestion(instrument == $instrument)
    CanAfford(instrumentId == $instrument.id)
    LikesGenre($genreId : genreId)
    CharacteristicInstrument(genreId == $genreId, instrumentId == $instrument.getId())
    not BlacklistedKindOfInstruments(kindCode == $instrument.kind)

    not TakesTooMuchTimeToLearn(instrumentId == $instrument.id)
    not PlaysInstrument(instrumentId == $instrument.id)
    not TakesTooMuchSpace(instrumentId == $instrument.id)
    not IsTooHeavy(instrumentId == $instrument.getId())
//    (sedentary || (nomad && not IsHeavy(instrumentId == $instrument.name)))
//    not IsTooLoud((instrumentId == $instrument.name)
//    not BlacklistedCategoryOfInstruments(categoryCode == $instrument.category)
then
    insert(new InstrumentSuggestion($instrument));
end

function boolean wasYoungAdultDuringGoldenAge(DateOfBirth dob, Genre g) {
    Integer yearOfBirth = dob.getValue().getYear();
    int yearOfTwenty = yearOfBirth + 20;
    int yearOfThirty = yearOfBirth + 30;
    return (g.getGoldenAgeStartingYear() >= yearOfTwenty && g.getGoldenAgeEndingYear() <= yearOfThirty)
        || (yearOfTwenty <= g.getGoldenAgeStartingYear() && g.getGoldenAgeStartingYear() <= yearOfThirty)
        || (yearOfTwenty <= g.getGoldenAgeEndingYear() && g.getGoldenAgeEndingYear() <= yearOfThirty)
        ;
}
