import com.mbenabda.techwatch.testES.domain.Instrument
import com.mbenabda.techwatch.testES.facts.weight.*
import com.mbenabda.techwatch.testES.facts.answers.*

rule "human weight limit"
when
    not(WeightLimit())
then
    insert(new WeightLimit(Float.valueOf(50)));
end

rule "intrument is heavy"
when
    WeightLimit( $limit: value )
    $instrument : Instrument( averageWeight >= $limit)
then
    insert(new IsHeavy($instrument.getId()));
end

rule ""
when
    $instrument: Instrument()
    IsNomad()
    IsHeavy(instrumentId == $instrument.getId())
then
    insert(new IsTooHeavy($instrument.getId()));
end
